/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playerz;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import main.Game;
import main.MusicPlayer;

/**
 *
 * @author user
 */
public class Loading2 extends javax.swing.JFrame {

    /**
     * Creates new form loading2
     */
    MusicPlayer musicPlayer = new MusicPlayer();
    public Loading2() {
        musicPlayer.play3(true);
        initComponents();
        Thread t = new Thread(new Runnable(){
            @Override
            public void run(){
                
                for(int i = 0; i<=100; i++){
                    
                    try {
                        progressbar.setValue(i);  
                        Thread.sleep(130);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoadScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(i == 100){
                    new Game();
                    dispose(true);
                    }
                
                }
                
            }
            
        });
        t.start();
    }
    
    private void dispose(boolean j){
        if (j) {
            musicPlayer.play3(false);
        SwingUtilities.invokeLater(() -> this.dispose());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressbar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1664, 896));
        setMinimumSize(new java.awt.Dimension(1664, 896));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1664, 896));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1664, 896));
        jPanel1.setMinimumSize(new java.awt.Dimension(1664, 896));
        jPanel1.setPreferredSize(new java.awt.Dimension(1664, 896));
        jPanel1.setLayout(null);

        progressbar.setBackground(new java.awt.Color(0, 0, 0));
        progressbar.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        progressbar.setForeground(new java.awt.Color(0, 255, 255));
        progressbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 102, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(255, 102, 0), new java.awt.Color(255, 51, 0)));
        progressbar.setStringPainted(true);
        jPanel1.add(progressbar);
        progressbar.setBounds(100, 760, 1430, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\keyboardbgimgg.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 400, 780, 280);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\11111111111.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 20, 1010, 240);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\legendary.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(620, 220, 460, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\load2bgimg.gif")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -120, 1670, 1020);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1664, 896);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables
}
