/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playerz;

import inputs.KeyboardInputs;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import main.MusicPlayer;

/**
 *
 * @author user
 */
public class LoadScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadScreen
     */
     MusicPlayer musicPlayer = new MusicPlayer();
    public LoadScreen() {
           
        musicPlayer.play3(true);
        initComponents();
        Thread t = new Thread(new Runnable(){
            @Override
            public void run(){
                
                for(int i = 0; i<=100; i++){
                    try {
                        progressbar.setValue(i);  
                        Thread.sleep(90);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoadScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(i == 100){
                    CharacterPick charp1 = new CharacterPick();
                    charp1.setLocationRelativeTo(null);
                    charp1.setVisible(true);
                    dispose(true);
                    }
                
                }
                
            }
            
        });
        t.start();
        
    }
    
    private void dispose(boolean j){
        if (j) {
            musicPlayer.play3(false);
        SwingUtilities.invokeLater(() -> this.dispose());
    }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressbar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1664, 896));
        setMinimumSize(new java.awt.Dimension(1664, 896));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1664, 896));
        jPanel1.setMinimumSize(new java.awt.Dimension(1664, 896));
        jPanel1.setPreferredSize(new java.awt.Dimension(1664, 896));
        jPanel1.setLayout(null);

        progressbar.setBackground(new java.awt.Color(0, 0, 0));
        progressbar.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        progressbar.setForeground(new java.awt.Color(255, 204, 0));
        progressbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(204, 0, 51), new java.awt.Color(255, 102, 0)));
        progressbar.setStringPainted(true);
        jPanel1.add(progressbar);
        progressbar.setBounds(190, 720, 1328, 54);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\underworldlegendstxt.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 50, 510, 187);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\player2keyinfo.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 370, 821, 280);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\player1keyinfo.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(720, 80, 780, 280);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 100));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(-60, 80, 1730, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\backgimg123.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-170, 0, 1840, 1070);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1664, 896);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar progressbar;
    // End of variables declaration//GEN-END:variables
}
